name: Run janitor on schedule

on:
  schedule:
    - cron: '11 0 * * 1'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest image
        run: docker pull caian/vrelease-janitor:latest

      - name: Run janitor
        run: docker run -e GITHUB_AUTH_TOKEN="${{ secrets.AUTH_TOKEN }}" caian/vrelease-janitor
